sudo: required
services:
  - docker
env:
  global:
    - CONTAINER_IMAGE=sgs-ci-build-image

before_script:
  - export BUILD_DATE=$(date '+%d/%m/%Y %T UTC' -u)
  - docker pull $CONTAINER_IMAGE || true

script:
  - docker build --cache-from $CONTAINER_IMAGE:latest --tag $USERNAME/$CONTAINER_IMAGE:$TRAVIS_COMMIT .

after_script:
  - docker images

before_deploy:
  - docker login -u $USERNAME -p $PASSWORD
  - docker tag $CONTAINER_IMAGE $CONTAINER_IMAGE:latest

deploy:
  provider: script
  script: 
    - docker push $USERNAME/$CONTAINER_IMAGE:$TRAVIS_COMMIT
    - docker push $USERNAME/$CONTAINER_IMAGE:latest
  on:
    branch: master