sudo: required
services:
  - docker
env:
  global:
    - CONTAINER_IMAGE=sgs-ci-build-image

before_script:
  - export BUILD_DATE=$(date '+%d/%m/%Y %T UTC' -u)
  - docker pull $CONTAINER_IMAGE || true

script:
  - docker build --cache-from $CONTAINER_IMAGE:latest --build-arg BUILD_DATE="${BUILD_DATE}" --build-arg TRAVIS_COMMIT="${TRAVIS_COMMIT}" --tag $USERNAME/$CONTAINER_IMAGE:$TRAVIS_COMMIT --tag $USERNAME/$CONTAINER_IMAGE:latest .

after_script:
  - docker images

before_deploy:
  - echo $PASSWORD | docker login -u $USERNAME --password-stdin

deploy:
  provider: script
  script: docker push $USERNAME/$CONTAINER_IMAGE:$TRAVIS_COMMIT && docker push $USERNAME/$CONTAINER_IMAGE:latest
  on:
    branch: master